---
- hosts: mesos-cluster
  become: yes

  tasks:
  - name: Copy the new resolve.conf file
    copy: src=template/resolve.conf dest=/etc/resolv.conf
  
  - name: Change DNS entry in ipcfg
    lineinfile: path=/etc/sysconfig/network-scripts/ifcfg-enp0s3 regexp='^DNS1' line='DNS1=192.168.0.101'
  
  - name: remove the extra DNS line
    lineinfile: path=/etc/sysconfig/network-scripts/ifcfg-enp0s3 regexp='^DNS2' state=absent   
