---
- hosts: k8s-cluster
  gather_facts: no
  become: yes

  tasks:
  - name: Copy hostfiles
    copy: 
      src: templates/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
  - name: create user
    user: name=ansible password=$6$mjnKHkdQAUTLw9g1$JDReR31/MkcNFt8AFLuGgbSDZxA60HbKOphZqdcdMSumAVMR80MZYsOLCJtA/H8Vl68iQqkfC1VxSkJfSUXho1 group=wheel
  - name: replace the sudoers file in destinations
    copy: src=/home/siju/Projects/Ansible/sudoers dest=/etc/sudoers owner=root group=root mode=0440

  - name: generate ssh key for ansible
    become_user: ansible
    command: ssh-keygen -t rsa -f /home/ansible/.ssh/id_rsa -q -N ""
    args:
      creates: /home/ansible/.ssh

  - name: Touch file authorized_keys
    ansible.builtin.file:
     path: /home/ansible/.ssh/authorized_keys
     state: touch
     owner: ansible
     group: ansible
     mode: '0644'

  - name: read ssh key to public_key variable 
    slurp: src={{ item }}
    with_items: 
    - /home/siju/.ssh/id_rsa.pub
    register: public_key
    delegate_to: localhost
 
  - name: copy keys to remote machine
    lineinfile:
      dest: /home/ansible/.ssh/authorized_keys
      line: "{{ item.content | b64decode }}"
    with_items: "{{ public_key.results }}"
   

