---
- hosts: proxy
  gather_facts: no
  become: yes

  tasks:
  - name: Ensure yum-utils installed
    ansible.builtin.yum: 
      name:
        yum-utils
      state:
        present 
  - name: Install HAPROXY modules
    ansible.builtin.yum:
      name:
        - haproxy
        - net-tools     
      state: present  
  - name: Copy hostfiles
    copy: 
      src: templates/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
  - name: Copy haproxy config
    copy: 
      src: templates/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0644'
  - name: Disable firewalld
    systemd:
      name: firewalld
      port: 8081/tcp
      permanent: yes
      state: enabled
  - name: disable SELinux
    ansible.builtin.shell: setenforce 0 && sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux
  - name: reload the systemd daemon 
    ansible.builtin.shell: systemctl daemon-reload
  - name: Enable all service
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items:
      - haproxy

  







