---
- hosts: proxy
  gather_facts: no
  become: yes
  tasks:
  - name: Ensure yum-utils installed
    ansible.builtin.yum: 
      name:
        yum-utils        
      state:
        present 
  - name: Install HAPROXY modules
    ansible.builtin.yum:
      name:
        - haproxy
        - net-tools     
      state: present  
  - name: Copy hostfiles
    copy: 
      src: templates/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
  - name: Copy haproxy config
    copy: 
      src: templates/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0644'
  - name: Open ports in firewalld
    firewalld:
      port: 6443/tcp
      permanent: yes
      state: enabled
      immediate: yes
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive
  - name: reload the systemd daemon 
    ansible.builtin.shell: systemctl daemon-reload
  - name: Enable all service
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items:
      - haproxy
  - name: Add kubernetes repo 
    copy: 
      src: templates/kuberepo
      dest: /etc/yum.repos.d/kubernetes.repo
      owner: root
      group: root
      mode: '0644'
  - name: Install kubectl and other binaries
    ansible.builtin.yum:
      name:
        - kubectl 
      state: present
      disable_excludes: kubernetes 

  







